#!/usr/bin/env bash
# Script displays "To infinity and beyond" indefinitely with
# a sleep 2 in between each iteration.

# responds to SIGTERM with "I am invincible!!!"

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
