#!/usr/bin/env bash
# Script to update the hosts file

cp /etc/hosts ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
